# Header
menu:
  Home: /
  Archives: /archives
  Life: /life
  About: /about
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
widgets:
# - life
# - about
# - archive

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
favicon: /favicon.png
duoshuo: true
duoshuo_appid: 'cyt3kgXme'
